name: 'book-platform'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: book-platform-db
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - book-platform-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-platform-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
    networks:
      - book-platform-network

networks:
  book-platform-network:
    name: book-platform-network
    driver: bridge
